### ISSUE TITLE
[MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: UserStore@1.user

### ISSUE THREAD

**Issue by firozansari** [zvikfir/MyWay#21]
I am getting ```changing (observed) observable values without using an action is not allowed``` error when I access the home page after running the client. MyWay-server is running fine on my local machine.

 ```
ready - started server on 0.0.0.0:3000, url: http://localhost:3000
info  - Loaded env from D:\GitHub\MyWay\MyWay-client\.env
info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
event - compiled successfully
event - build page: /dogs
wait  - compiling...
event - compiled successfully
[MobX] Since strict-mode is enabled, changing (observed) observable values without using an action is not allowed. Tried to modify: UserStore@1.user
D:\GitHub\MyWay\MyWay-client\node_modules\next\dist\client\router.js:116
        throw new Error(message);
              ^

Error: No router instance found.
You should only use "next/router" on the client side of your app.

    at getRouter (D:\GitHub\MyWay\MyWay-client\node_modules\next\dist\client\router.js:116:15)
    at Object.singletonRouter.<computed> [as push] (D:\GitHub\MyWay\MyWay-client\node_modules\next\dist\client\router.js:93:24)
    at D:\GitHub\MyWay\MyWay-client\.next\server\pages\_app.js:2712:176
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
```

Any pointer to resolve the issue is much appreciated.

**Comment by zvikfir** [comment]
You are right. I was able to restore the issue. It was caused due to incorrect use of the Mobx library.

More info - https://stackoverflow.com/a/64771774
